tunnel: cryptocraze-tunnel
credentials-file: /home/tkachevartem/.cloudflared/cryptocraze-tunnel.json

ingress:
  # Frontend - статические файлы и SPA маршруты
  - hostname: your-domain.com
    service: http://localhost:80
    originRequest:
      httpHostHeader: your-domain.com
      noTLSVerify: true
  
  # API маршруты
  - hostname: your-domain.com
    path: /api/*
    service: http://localhost:3001
    originRequest:
      httpHostHeader: your-domain.com
      noTLSVerify: true
  
  # WebSocket для Socket.IO
  - hostname: your-domain.com
    path: /socket.io/*
    service: http://localhost:3001
    originRequest:
      httpHostHeader: your-domain.com
      noTLSVerify: true
  
  # Fallback для остальных запросов
  - service: http_status:404