# Simplified single-container setup for testing
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      - NODE_ENV=production
      - PORT=1111
      # Use in-memory/mock services for simplification
      - DATABASE_URL=sqlite://memory
      - REDIS_URL=redis://localhost:6379
      - CLICKHOUSE_URL=http://localhost:8123
      - CLICKHOUSE_DATABASE=cryptocraze_analytics
      - ENABLE_REDIS_SCALING=false
      - SKIP_MIGRATIONS=true
      - STATIC_ONLY=false
      - DISABLE_ADMIN_AUTH=true
      - GOOGLE_CLIENT_ID=707632794493-5lhl2avka63s62n4nje0qlvg7vd90dc4.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=http://localhost:1111/api/auth/google/callback
      - SESSION_SECRET=production-secret-change-me-123456789
      - FRONTEND_URL=http://localhost:1111
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    network_mode: host