export const symbolToCoinId: Record<string, string> = {
  BTCUSDT: 'bitcoin',
  ETHUSDT: 'ethereum',
  SOLUSDT: 'solana',
  BNBUSDT: 'binancecoin',
  ADAUSDT: 'cardano',
  XRPUSDT: 'ripple',
  DOGEUSDT: 'dogecoin',
  MATICUSDT: 'matic-network',
  DOTUSDT: 'polkadot',
  TRXUSDT: 'tron',
  LTCUSDT: 'litecoin',
  AVAXUSDT: 'avalanche-2',
  SHIBUSDT: 'shiba-inu',
  LINKUSDT: 'chainlink',
  ATOMUSDT: 'cosmos',
  XMRUSDT: 'monero',
  UNIUSDT: 'uniswap',
  BCHUSDT: 'bitcoin-cash',
  ETCUSDT: 'ethereum-classic',
  FILUSDT: 'filecoin',
  APTUSDT: 'aptos',
  NEARUSDT: 'near',
  LDOUSDT: 'lido-dao',
  ARBUSDT: 'arbitrum',
  OPUSDT: 'optimism',
  SUIUSDT: 'sui',
  PEPEUSDT: 'pepe',
  INJUSDT: 'injective-protocol',
  STXUSDT: 'stacks',
  RUNEUSDT: 'thorchain',
  // ...добавляй по необходимости
};